# Generated by Django 6.1.1 on 2026-09-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='agentprofile',
            table='agent_profiles',
        ),
        migrations.AlterModelTable(
            name='assignment',
            table='assignments',
        ),
        migrations.AlterModelTable(
            name='locationlog',
            table='location_logs',
        ),
        migrations.AlterModelTable(
            name='performancelog',
            table='performance_logs',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
